#
# This file contains configuration flags to customize your site
#
future: true
source: _posts
# Name of your site (displayed in the header)
name: MathForFuture.com
title: MathForFuture.com - Math for a Changing World

# use this url when working off GitHub
#url:                http://www.mathforfuture.com

# Use this url when working locally
url: ~

# Short bio or description (displayed in the header)
description: "Free high school math practice problems aligned with the Alberta Education Program of Study fror high school mathematics."

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: images/avatar.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: www.mathforfuture.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Sest the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude: [vendor]

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
